[project]
name = "maskcraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic-settings>=2.14.1",
    "pyside6>=6.11.1",
    "requests>=2.34.2",
]

[project.scripts]
maskcraft = "maskcraft:main"

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"
